[package]
name = "sports"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
futures = "0.3"
clap = { version = "4.4", features = ["derive"] }
colored = "2"
